# all available settings of specific linters
linters:
  disable:
    - gomoddirectives
    - godot
    - testpackage
    - nakedret
    - funlen
    - noctx
    - gofumpt
    - gocritic
    - paralleltest
    - wrapcheck
    - exhaustivestruct
    - maligned
    - interfacer
    - forbidigo
    - ifshort
    - wastedassign
    - scopelint
    - golint
    - gci
    - nolintlint
    # todo - remove in future
    - gosimple
    - gosec
    - exhaustive
    - thelper
    - godox

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - dupl
        - gochecknoglobals
    - path: pkg/gost3410/
      linters:
        - wsl
        - gomnd
        - gochecknoglobals
        - errcheck
        - staticcheck
        - ineffassign
        - stylecheck
        - goerr113
        - dupl
        - gochecknoinits
        - lll
        - revive
        - nlreturn
    - path: pkg/gost3413/
      linters:
        - wsl
        - gomnd
        - gochecknoglobals
        - errcheck
        - staticcheck
        - ineffassign
        - stylecheck
        - goerr113
        - dupl
        - gochecknoinits
        - lll
        - revive
        - nlreturn
    - path: pkg/gost28147/
      linters:
        - wsl
        - gomnd
        - gochecknoglobals
        - errcheck
        - staticcheck
        - ineffassign
        - stylecheck
        - goerr113
        - dupl
        - gochecknoinits
        - lll
        - revive
        - nlreturn
    - path: pkg/gost341194/
      linters:
        - wsl
        - gomnd
        - gochecknoglobals
        - errcheck
        - staticcheck
        - ineffassign
        - stylecheck
        - goerr113
        - dupl
        - gochecknoinits
        - lll
        - revive
        - nlreturn
    - path: pkg/gost341264/
      linters:
        - wsl
        - gomnd
        - gochecknoglobals
        - errcheck
        - staticcheck
        - ineffassign
        - stylecheck
        - goerr113
        - dupl
        - gochecknoinits
        - lll
        - revive
        - nlreturn
    - path: pkg/gost3412128/
      linters:
        - wsl
        - gomnd
        - gochecknoglobals
        - errcheck
        - staticcheck
        - ineffassign
        - stylecheck
        - goerr113
        - dupl
        - gochecknoinits
        - lll
        - revive
        - nlreturn
    - path: pkg/gost34112012256/
      linters:
        - wsl
        - gomnd
        - gochecknoglobals
        - errcheck
        - staticcheck
        - ineffassign
        - stylecheck
        - goerr113
        - dupl
        - gochecknoinits
        - lll
        - revive
        - nlreturn
    - path: pkg/gost34112012512/
      linters:
        - wsl
        - gomnd
        - gochecknoglobals
        - errcheck
        - staticcheck
        - ineffassign
        - stylecheck
        - goerr113
        - dupl
        - gochecknoinits
        - lll
        - revive
        - nlreturn
    - path: pkg/mgm/
      linters:
        - wsl
        - gomnd
        - gochecknoglobals
        - errcheck
        - staticcheck
        - ineffassign
        - stylecheck
        - goerr113
        - unparam
        - dupl
        - gochecknoinits
        - lll
        - revive
        - nlreturn
    - path: pkg/prfplus/
      linters:
        - wsl
        - gomnd
        - gochecknoglobals
        - errcheck
        - staticcheck
        - ineffassign
        - stylecheck
        - goerr113
        - dupl
        - gochecknoinits
        - lll
        - revive
        - nlreturn
    - path: internal/pkg/gost34112012/
      linters:
        - wsl
        - gomnd
        - gochecknoglobals
        - errcheck
        - staticcheck
        - ineffassign
        - stylecheck
        - goerr113
        - dupl
        - gochecknoinits
        - lll
        - revive
        - nlreturn

# all available settings of specific linters
linters-settings:
  gocognit:
    # todo - make lower - 10 in future
    min-complexity: 65
  cyclop:
    # todo - make lower - 10 in future
    max-complexity: 35